name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  TAG: v1
  REPO: quan787/wmpl

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: login
        run: docker login --username=${{secrets.DOCKER_USER}} --password=${{secrets.DOCKER_PASSWORD}}
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{env.REPO}}:${{env.TAG}}
      - name: push
        run: docker push ${{env.REPO}}:${{env.TAG}}

